trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: PowerShell@2
  displayName: 'Install latest NuGet'
  inputs:
    targetType: 'inline'
    script: 'Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v6.0.0-preview3/nuget.exe" -OutFile .\.nuget\nuget.exe'

- task: NuGetAuthenticate@0

- task: PowerShell@2
  displayName: Restore packages
  inputs:
    targetType: 'inline'
    script: ' .\.nuget\nuget.exe restore'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: './NuGet.Config'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: False
    zipAfterPublish: False
    arguments: '-r linux-x64 --output $(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  displayName: Send Artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Dexter'