using Dexter.Abstractions;
using System.Collections.Generic;

namespace Dexter.Configurations {

    /// <summary>
    /// The GreetFurConfiguration specifies the information relating to the Google Sheets data required.
    /// </summary>
    public class GreetFurConfiguration : JSONConfiguration {

        /// <summary>
        /// The ApplicationName is the name of the application specified when creating the credentials.json file.
        /// </summary>
        public string ApplicationName { get; set; }

        /// <summary>
        /// The CredentialFile is the place the credential file generated by Google is stored.
        /// </summary>
        public string CredentialFile { get; set; }

        /// <summary>
        /// The TokenFile is the place the token file generated by the program from the credentials is stored.
        /// </summary>
        public string TokenFile { get; set; }

        /// <summary>
        /// The SpreadSheetID is the ID of the GreetFur spreadsheet chart.
        /// </summary>
        public string SpreadSheetID { get; set; }

        /// <summary>
        /// The FortnightSpreadsheet represents the title of the spreadsheet containing all the fortnightly data for the GreetFur.
        /// </summary>
        public string FortnightSpreadsheet { get; set; }

        /// <summary>
        /// The IDColumnIndex is the index of the column that contains all the UserIDs
        /// </summary>
        public string IDColumnIndex { get; set; }

        /// <summary>
        /// The Information dictionary stores all the column indexes and their respective names.
        /// </summary>
        public Dictionary<string, int> Information { get; set; }
    }

}
